repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files

  # Frontend
  - repo: local
    hooks:
    -   id: local-biome-check
        name: biome check
        entry: bash -c 'cd frontend && npx biome check . --write --no-errors-on-unmatched'
        language: system
        types: [text]
        files: ^frontend/.*\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$

    -   id: typecheck-frontend
        name: typecheck frontend
        entry: bash -c 'cd frontend && npm run typecheck'
        language: system
        pass_filenames: false
        always_run: true

  # Backend
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [--fix, backend]
        pass_filenames: false
        always_run: true
      - id: ruff-format
        args: [backend]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: mypy-backend
        name: mypy backend
        entry: uv run --project backend mypy --config-file=backend/pyproject.toml backend/app
        language: system
        pass_filenames: false
        always_run: true
