import logging

import httpx
from rag_service_api import Client, DirectQueryRequest, HTTPValidationError, direct_query

from app.core.config import settings
from app.services.prompt_service import PromptService

logger = logging.getLogger(__name__)


class LlmServiceError(RuntimeError):
    pass


class LlmService:
    def __init__(self) -> None:
        self.prompt_service = PromptService()
        self.client = Client(
            base_url=settings.rag_service_url,
            timeout=httpx.Timeout(60.0),
            raise_on_unexpected_status=True,
        )

    async def generate_suggestion(self, email_text: str) -> str:
        """Call the RAG service to obtain an AI-generated answer suggestion.

        Raises:
            LlmServiceError: If communication with the RAG service fails or
                an invalid response is returned.
        """
        query_text = self.prompt_service.get_reply_prompt(email_text)

        request_body = DirectQueryRequest(
            documents_text=email_text,
            query=query_text,
            llm_model=settings.llm_model,
        )

        try:
            response = await direct_query.asyncio(
                client=self.client,
                body=request_body,
            )

            if response is None:
                raise LlmServiceError("RAG Service returned no response.")

            if isinstance(response, HTTPValidationError):
                raise LlmServiceError(f"RAG Service validation error: {response.detail}")

            reply = response.additional_properties.get(
                "reply"
            ) or response.additional_properties.get("answer")
            return str(reply or "No response generated by the model.")

        except Exception as exc:
            if isinstance(exc, LlmServiceError):
                raise
            logger.error(
                "RAG Service Request failed. URL: %s, Error: %s",
                self.client._base_url,
                exc,
            )
            raise LlmServiceError(f"RAG Service request failed: {exc}") from exc
