import logging
from datetime import UTC, datetime

import httpx
from rag_service_api import Client, DirectQueryRequest, HTTPValidationError, direct_query

from app.api.schemas.chat_schema import ChatMessageSchema
from app.core.config import settings
from app.core.datetime_utils import format_datetime_de
from app.services.vector_store_service import VectorStoreService

logger = logging.getLogger(__name__)


class LlmServiceError(RuntimeError):
    pass


class LlmService:
    def __init__(self, vector_store: VectorStoreService) -> None:
        self.vector_store = vector_store
        self.client = Client(
            base_url=settings.rag_service_url,
            timeout=httpx.Timeout(60.0),
            raise_on_unexpected_status=True,
        )

    @staticmethod
    def _today_line() -> str:
        """A 'today is ...' anchor so the model can relate relative dates

        (e.g. "morgen", "heute") in the user's message to concrete calendar
        dates. Always included, regardless of whether calendar data is
        available, since knowing the current date is baseline context for
        any request - not just meeting-scheduling ones.
        """
        return f"Heute ist {format_datetime_de(datetime.now(UTC))} Uhr."

    async def _get_kb_context(
        self,
        query: str,
        k: int = 3,
        header: str = "Relevant Information from Knowledge Base:",
    ) -> str:
        """Helper to fetch and format context from the vector store."""
        if not query:
            return ""
        results = await self.vector_store.search(query, k=k)
        if not results:
            return ""
        return f"\n\n{header}\n" + "\n".join([r.content for r in results])

    async def chat(self, messages: list[ChatMessageSchema], extra_context: str = "") -> str:
        """Process a conversation history and return an AI-generated reply.

        Integrates context from the knowledge base based on the latest user message.
        `extra_context` (e.g. calendar availability) is appended verbatim.
        """
        if not messages:
            return "No messages provided."

        # Get the last user message for RAG context retrieval
        user_query = ""
        for msg in reversed(messages):
            if msg.role == "user":
                user_query = msg.content
                break

        kb_context = await self._get_kb_context(user_query, k=3)

        # Construct the conversation history for the model
        # The RAG service might expect a single 'query' and 'documents_text'
        # We will format the conversation into the query field.
        conversation_history = ""
        for msg in messages:
            role_name = "User" if msg.role == "user" else "Assistant"
            conversation_history += f"{role_name}: {msg.content}\n"

        request_body = DirectQueryRequest(
            documents_text=f"{self._today_line()}{kb_context}{extra_context}",
            query=conversation_history + "\nAssistant:",
            llm_model=settings.llm_model,
        )

        logger.info("Sending chat request to RAG service: %s", request_body.to_dict())

        try:
            response = await direct_query.asyncio(
                client=self.client,
                body=request_body,
            )

            if response is None:
                raise LlmServiceError("RAG Service returned no response.")

            if isinstance(response, HTTPValidationError):
                logger.error("RAG Service validation error: %s", response.to_dict())
                raise LlmServiceError(f"RAG Service validation error: {response.detail}")

            reply = response.additional_properties.get(
                "reply"
            ) or response.additional_properties.get("answer")
            return str(reply or "No response generated by the model.")

        except Exception as exc:
            if isinstance(exc, LlmServiceError):
                raise
            logger.error("Chat request failed: %s", exc)
            raise LlmServiceError(f"Chat request failed: {exc}") from exc
