from pydantic import Field

from app.api.schemas.base_schema import BaseSchema
from app.api.schemas.calendar_schema import MeetingProposalSchema


class HealthResponseSchema(BaseSchema):
    status: str = Field(description="Current status of the backend.", examples=["ok"])


class EmailSuggestionRequestSchema(BaseSchema):
    email_content: str = Field(
        min_length=1,
        description="The full text of the email for which a suggestion should be generated.",
        examples=["Hello, can we move the meeting tomorrow to 2 PM? Best regards, Max"],
    )
    attendees: list[str] = Field(
        default_factory=list,
        description="Email addresses of the other recipients (To/Cc), used to check "
        "everyone's calendar availability for meeting-time suggestions.",
        examples=[["alice@contoso.com"]],
    )


class EmailSuggestionResponseSchema(BaseSchema):
    suggested_reply: str = Field(
        description="The professionally formatted answer suggestion generated by the AI.",
        examples=["Hello Max,\n\nyes, 2 PM works for me. See you tomorrow!\n\nBest regards"],
    )
    meeting_proposal: MeetingProposalSchema | None = Field(
        default=None,
        description="A concrete meeting suggestion, if the email contained a meeting request.",
    )


class ErrorResponseSchema(BaseSchema):
    detail: str = Field(
        description="A detailed error message explaining what went wrong.",
        examples=["RAG Service request failed: connection timeout"],
    )
