from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class BaseSchema(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True,
    )


class HealthResponseSchema(BaseSchema):
    status: str = Field(description="Current status of the backend.", examples=["ok"])


class EmailSuggestionRequestSchema(BaseSchema):
    email_content: str = Field(
        min_length=1,
        description="The full text of the email for which a suggestion should be generated.",
        examples=["Hello, can we move the meeting tomorrow to 2 PM? Best regards, Max"],
    )


class EmailSuggestionResponseSchema(BaseSchema):
    suggested_reply: str = Field(
        description="The professionally formatted answer suggestion generated by the AI.",
        examples=["Hello Max,\n\nyes, 2 PM works for me. See you tomorrow!\n\nBest regards"],
    )


class ErrorResponseSchema(BaseSchema):
    detail: str = Field(
        description="A detailed error message explaining what went wrong.",
        examples=["RAG Service request failed: connection timeout"],
    )
